version: "3.9"

services:
  web:
    build: .
    container_name: llmapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload


  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/
    healthcheck:                    
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s                   
      timeout: 3s
      retries: 5                   
      start_period: 5s               

volumes:
  pg_data: